DROP TABLE IF EXISTS group_members CASCADE;
CREATE TABLE group_members(
  id SERIAL PRIMARY KEY NOT NULL,
  uesr_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE
);