DROP TABLE IF EXISTS posts CASCADE;
CREATE TABLE posts (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  workout_id INTEGER REFERENCES workouts(id) ON DELETE CASCADE NOT NULL,
  group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE
);