DROP TABLE IF EXISTS comments CASCADE;
CREATE TABLE comments (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  workout_id INTEGER REFERENCES workouts(id) ON DELETE CASCADE NOT NULL,
  message TEXT NOT NULL
);